# Generated by Django 2.2.28 on 2022-04-27 08:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2022, 4, 27, 11, 55, 37, 338036), verbose_name='Опубликована'),
        ),
    ]
